spring:
  application:
    name: notification-service

  cloud:
    config:
      uri: http://config-server:8888
    eureka:
      client:
        service-url:
          defaultZone: http://eureka-server:8761/eureka
        register-with-eureka: true
        fetch-registry: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.example.com
    port: 587
    username: your_email@example.com
    password: your_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8082
